name: Complex

on: push

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - run: date
  windows:
    runs-on: windows-latest
    steps:
    - run: date
  macos:
    runs-on: macos-latest
    steps:
    - run: date
  testos:
    runs-on: ubuntu-latest
    needs: [windows]
    steps:
    - run: echo "this is working!"
