name: Using Actions

on: [dispatch_workflow]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out this code - which means to bring the code to the repo
        uses: actions/checkout@v2

      - name: Python Syntax Checker
        uses: cclauss/Find-Python-syntax-errors-action@master

